# Generated by Django 2.0.2 on 2018-07-01 07:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20180628_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('hospital', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Med_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reason', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date(2018, 7, 1))),
                ('end_date', models.DateField(default=datetime.date(2018, 7, 1))),
                ('dosage_perday', models.IntegerField()),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Med_data')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_num', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_visit', models.DateField(blank=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Doctor')),
                ('medicines', models.ManyToManyField(to='catalog.Medicine')),
            ],
        ),
        migrations.CreateModel(
            name='visited',
            fields=[
                ('date_visited', models.DateField(default=datetime.date(2018, 7, 1))),
                ('what_for', models.CharField(blank=True, max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID', primary_key=True, serialize=False)),
                ('doctor_visited', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Doctor')),
                ('prescri', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Prescription')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='visits',
            field=models.ManyToManyField(to='catalog.visited'),
        ),
    ]
