# Generated by Django 2.0.2 on 2018-07-02 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20180701_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='end_date',
            field=models.DateField(default=datetime.date(2018, 7, 2)),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='start_date',
            field=models.DateField(default=datetime.date(2018, 7, 2)),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='date_visited',
            field=models.DateField(default=datetime.date(2018, 7, 2)),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medicines',
            field=models.ManyToManyField(blank=True, to='catalog.Medicine'),
        ),
    ]
