# Generated by Django 2.0.2 on 2018-07-04 10:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0025_auto_20180702_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='user_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='end_date',
            field=models.DateField(default=datetime.date(2018, 7, 4)),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='start_date',
            field=models.DateField(default=datetime.date(2018, 7, 4)),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='date_visited',
            field=models.DateField(default=datetime.date(2018, 7, 4)),
        ),
    ]
